### ISSUE TITLE
Add ONLINE to Bit By Bit

### ISSUE THREAD

**Issue by roerohan** [csivitu/CSIWebsite2.0#3]
- Add ONLINE to BIT BY BIT, like in other online events.
- Maybe put the new CTF logo for CSICTF?

@shaarangg

**Comment by shaarangg** [comment]
- Added Online to BBB

- Will update after the event is completed

**Comment by thebongy** [comment]
#5 merged

**Comment by thebongy** [comment]
@roerohan how do you want to do it for csictf? After the event, or right now itself, with details for the event (as a new CTF event, old one cay stay on the page)?

**Comment by roerohan** [comment]
Maybe we can rename the current CTF to CSICTF 2019 and the new one to CSICTF 2020, with the new logo?
@thebongy @shaarangg

**Comment by thebongy** [comment]
Sounds good to me

**Comment by shaarangg** [comment]
Changed the name of CTF to CSI CTF 2019

**Comment by shaarangg** [comment]
Added CSI CTF 2020

**Comment by thebongy** [comment]
(Fixed in #7 )
